spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/med_voll
    username: postgres
    password: 121314
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
